"""
Enum dictionaries extracted from type_resolver.py.

Contains lookup tables for gameobject types, SAI events/actions/targets,
achievement criteria types, condition types, and emote mappings.

Imported by resolver modules to translate numeric IDs to human-readable names.
"""


# ============================================================================
# Gameobject type enum (GoType)
# ============================================================================
GO_TYPE_NAMES = {
    0: "DOOR", 1: "BUTTON", 2: "QUESTGIVER", 3: "CHEST", 4: "BINDER",
    5: "GENERIC", 6: "TRAP", 7: "CHAIR", 8: "SPELL_FOCUS", 9: "TEXT",
    10: "GOOBER", 11: "TRANSPORT", 12: "AREADAMAGE", 13: "CAMERA",
    14: "MAP_OBJECT", 15: "MO_TRANSPORT", 16: "DUEL_ARBITER",
    17: "FISHINGNODE", 18: "SUMMONING_RITUAL", 19: "MAILBOX",
    20: "AUCTIONHOUSE", 21: "GUARDPOST", 22: "SPELLCASTER",
    23: "MEETINGSTONE", 24: "FLAGSTAND", 25: "FISHINGHOLE",
    26: "FLAGDROP", 27: "MINI_GAME", 28: "LOTTERY_KIOSK",
    29: "CAPTURE_POINT", 30: "AURA_GENERATOR", 31: "DUNGEON_DIFFICULTY",
    32: "BARBER_CHAIR", 33: "DESTRUCTIBLE_BUILDING", 34: "GUILD_BANK",
    35: "TRAPDOOR",
}


# ============================================================================
# Condition enum mappings
# ============================================================================
_SOURCE_TYPE_NAMES = {
    0: "NONE", 1: "CREATURE_LOOT", 2: "DISENCHANT_LOOT", 3: "FISHING_LOOT",
    4: "GAMEOBJECT_LOOT", 5: "ITEM_LOOT", 6: "MAIL_LOOT", 7: "MILLING_LOOT",
    8: "PICKPOCKETING_LOOT", 9: "PROSPECTING_LOOT", 10: "REFERENCE_LOOT",
    11: "SKINNING_LOOT", 12: "SPELL_LOOT", 13: "SPELL_IMPLICIT_TARGET",
    14: "GOSSIP_MENU", 15: "GOSSIP_MENU_OPTION", 16: "CREATURE_TEMPLATE_VEHICLE",
    17: "SPELL", 18: "SPELL_CLICK_EVENT", 19: "QUEST_AVAILABLE",
    20: "GOSSIP_HELLO", 21: "VEHICLE_SPELL", 22: "SMART_EVENT",
    23: "NPC_VENDOR", 24: "SPELL_PROC", 25: "TERRAIN_SWAP", 26: "PHASE",
    27: "GRAVEYARD", 28: "PLAYER_LOOT", 29: "CREATURE_RESPAWN",
    30: "OBJECT_VISIBILITY",
}

_CONDITION_TYPE_NAMES = {
    0:  "NONE",
    1:  "AURA",
    2:  "ITEM",
    3:  "ITEM_EQUIPPED",
    4:  "ZONEID",
    5:  "REPUTATION_RANK",
    6:  "TEAM",
    7:  "SKILL",
    8:  "QUESTREWARDED",
    9:  "QUESTTAKEN",
    10: "DRUNKENSTATE",
    11: "WORLD_STATE",
    12: "ACTIVE_EVENT",
    13: "INSTANCE_INFO",
    14: "QUEST_NONE",
    15: "CLASS",
    16: "RACE",
    17: "ACHIEVEMENT",
    18: "TITLE",
    19: "SPAWNMASK",
    20: "GENDER",
    21: "UNIT_STATE",
    22: "MAPID",
    23: "AREADID",
    24: "CREATURE_TYPE",
    25: "SPELL",
    26: "PHASEMASK",
    27: "LEVEL",
    28: "QUEST_COMPLETE",
    29: "NEAR_CREATURE",
    30: "NEAR_GAMEOBJECT",
    31: "OBJECT_ENTRY_GUID",
    32: "TYPE_MASK",
    33: "RELATION_TO",
    34: "REACTION_TO",
    35: "DISTANCE_TO",
    36: "ALIVE",
    37: "HP_VAL",
    38: "HP_PCT",
    39: "REALM_ACHIEVEMENT",
    40: "IN_WATER",
    41: "TERRAIN_SWAP",
    42: "STAND_STATE",
    43: "DAILY_QUEST_DONE",
    44: "CHARMED",
    45: "PET_TYPE",
    46: "TAXI",
    47: "QUESTSTATE",
    48: "QUEST_OBJECTIVE_PROGRESS",
    49: "DIFFICULTY_ID",
    # AC custom conditions (100-105)
    100: "AC_START",
    101: "QUEST_SATISFY_EXCLUSIVE",
    102: "HAS_AURA_TYPE",
    103: "WORLD_SCRIPT",
    104: "AI_DATA",
    105: "PLAYER_QUEUED_RANDOM_DUNGEON",
}

# TYPEID enum (ObjectGuid.h) — used by CONDITION_OBJECT_ENTRY_GUID (type=31)
_TYPEID_NAMES = {
    0: "OBJECT",
    1: "ITEM",
    2: "CONTAINER",
    3: "UNIT",
    4: "PLAYER",
    5: "GAMEOBJECT",
    6: "DYNAMICOBJECT",
    7: "CORPSE",
}

# TYPEMASK enum (ObjectGuid.h) — used by CONDITION_TYPE_MASK (type=32)
_TYPEMASK_NAMES = {
    0x0001: "OBJECT",
    0x0002: "ITEM",
    0x0006: "CONTAINER",
    0x0008: "UNIT",
    0x0010: "PLAYER",
    0x0020: "GAMEOBJECT",
    0x0040: "DYNAMICOBJECT",
    0x0080: "CORPSE",
    0x00F0: "SEER",  # PLAYER | UNIT | DYNAMICOBJECT
}

# Class enum (SharedDefines.h) — used by CONDITION_CLASS (type=15)
_CLASS_NAMES = {
    0: "NONE", 1: "WARRIOR", 2: "PALADIN", 3: "HUNTER", 4: "ROGUE",
    5: "PRIEST", 6: "DEATH_KNIGHT", 7: "SHAMAN", 8: "MAGE",
    9: "WARLOCK", 11: "DRUID",
}

# Race enum (SharedDefines.h) — used by CONDITION_RACE (type=16)
_RACE_NAMES = {
    0: "NONE", 1: "HUMAN", 2: "ORC", 3: "DWARF", 4: "NIGHTELF",
    5: "UNDEAD", 6: "TAUREN", 7: "GNOME", 8: "TROLL",
    10: "BLOODELF", 11: "DRAENEI",
}

# Gender enum (SharedDefines.h) — used by CONDITION_GENDER (type=20)
_GENDER_NAMES = {0: "MALE", 1: "FEMALE", 2: "NONE"}


# ============================================================================
# SmartAI (SAI) enum mappings
# ============================================================================
_SAI_EVENT_NAMES = {
    0: "UPDATE_IC", 1: "UPDATE_OOC", 2: "HEALTH_PCT", 3: "MANA_PCT",
    4: "AGGRO", 5: "KILL", 6: "DEATH", 7: "EVADE", 8: "SPELLHIT",
    9: "RANGE", 10: "OOC_LOS", 11: "RESPAWN", 12: "TARGET_HEALTH_PCT",
    13: "VICTIM_CASTING", 14: "FRIENDLY_HEALTH", 15: "FRIENDLY_IS_CC",
    16: "FRIENDLY_MISSING_BUFF", 17: "SUMMONED_UNIT", 18: "TARGET_MANA_PCT",
    19: "ACCEPTED_QUEST", 20: "REWARD_QUEST", 21: "REACHED_HOME",
    22: "RECEIVE_EMOTE", 23: "HAS_AURA", 24: "TARGET_BUFFED",
    25: "RESET", 26: "IC_LOS", 27: "PASSENGER_BOARDED",
    28: "PASSENGER_REMOVED", 29: "CHARMED", 30: "CHARMED_TARGET",
    31: "SPELLHIT_TARGET", 32: "DAMAGED", 33: "DAMAGED_TARGET",
    34: "MOVEMENTINFORM", 35: "SUMMON_DESPAWNED", 36: "CORPSE_REMOVED",
    37: "AI_INIT", 38: "DATA_SET", 39: "ESCORT_START", 40: "ESCORT_REACHED",
    41: "TRANSPORT_ADDPLAYER", 42: "TRANSPORT_ADDCREATURE", 43: "TRANSPORT_REMOVE_PLAYER",
    44: "TRANSPORT_RELOCATE", 45: "INSTANCE_PLAYER_ENTER",
    46: "AREATRIGGER_ONTRIGGER",
    47: "QUEST_ACCEPTED", 48: "QUEST_OBJ_COMPLETION", 49: "QUEST_COMPLETION",
    50: "QUEST_REWARDED", 51: "QUEST_FAIL",
    52: "TEXT_OVER", 53: "RECEIVE_HEAL",
    54: "JUST_SUMMONED", 55: "ESCORT_PAUSED", 56: "ESCORT_RESUMED",
    57: "ESCORT_STOPPED", 58: "ESCORT_ENDED", 59: "TIMED_EVENT_TRIGGERED",
    60: "UPDATE", 61: "LINK", 62: "GOSSIP_SELECT", 63: "JUST_CREATED",
    64: "GOSSIP_HELLO", 65: "FOLLOW_COMPLETED", 66: "EVENT_PHASE_CHANGE",
    67: "IS_BEHIND_TARGET", 68: "GAME_EVENT_START", 69: "GAME_EVENT_END",
    70: "GO_STATE_CHANGED", 71: "GO_EVENT_INFORM", 72: "ACTION_DONE",
    73: "ON_SPELLCLICK", 74: "FRIENDLY_HEALTH_PCT",
    75: "DISTANCE_CREATURE", 76: "DISTANCE_GAMEOBJECT",
    77: "COUNTER_SET", 82: "SUMMONED_UNIT_DIES",
    101: "NEAR_PLAYERS", 102: "NEAR_PLAYERS_NEGATION",
    103: "NEAR_UNIT", 104: "NEAR_UNIT_NEGATION",
    105: "AREA_CASTING", 106: "AREA_RANGE", 107: "SUMMONED_UNIT_EVADE",
    108: "WAYPOINT_REACHED", 109: "WAYPOINT_ENDED",
    110: "IS_IN_MELEE_RANGE",
}

_SAI_ACTION_NAMES = {
    0: "NONE", 1: "TALK", 2: "SET_FACTION", 3: "MORPH_TO_ENTRY_OR_MODEL",
    4: "SOUND", 5: "PLAY_EMOTE", 6: "FAIL_QUEST", 7: "OFFER_QUEST",
    8: "SET_REACT_STATE", 9: "ACTIVATE_GOBJECT", 10: "RANDOM_EMOTE",
    11: "CAST", 12: "SUMMON_CREATURE", 13: "THREAT_SINGLE_PCT",
    14: "THREAT_ALL_PCT", 15: "CALL_AREAEXPLOREDOREVENTHAPPENS",
    17: "SET_EMOTE_STATE", 18: "SET_UNIT_FLAG", 19: "REMOVE_UNIT_FLAG",
    20: "AUTO_ATTACK", 21: "ALLOW_COMBAT_MOVEMENT", 22: "SET_EVENT_PHASE",
    23: "INC_EVENT_PHASE", 24: "EVADE", 25: "FLEE_FOR_ASSIST",
    26: "CALL_GROUPEVENTHAPPENS", 27: "COMBAT_STOP",
    28: "REMOVEAURASFROMSPELL", 29: "FOLLOW", 30: "RANDOM_PHASE",
    31: "RANDOM_PHASE_RANGE", 32: "RESET_GOBJECT",
    33: "CALL_KILLEDMONSTER", 34: "SET_INST_DATA", 35: "SET_INST_DATA64",
    36: "UPDATE_TEMPLATE", 37: "DIE", 38: "SET_IN_COMBAT_WITH_ZONE",
    39: "CALL_FOR_HELP", 40: "SET_SHEATH", 41: "FORCE_DESPAWN",
    42: "SET_INVINCIBILITY_HP_LEVEL", 43: "MOUNT_TO_ENTRY_OR_MODEL",
    44: "SET_INGAME_PHASE_MASK", 45: "SET_DATA", 46: "MOVE_FORWARD",
    47: "SET_VISIBILITY", 48: "SET_ACTIVE", 49: "ATTACK_START",
    50: "SUMMON_GO", 51: "KILL_UNIT", 52: "ACTIVATE_TAXI",
    53: "ESCORT_START", 54: "ESCORT_PAUSE", 55: "ESCORT_STOP",
    56: "ADD_ITEM", 57: "REMOVE_ITEM", 58: "INSTALL_AI_TEMPLATE",
    59: "SET_RUN", 60: "SET_FLY", 61: "SET_SWIM", 62: "TELEPORT",
    63: "SET_COUNTER", 64: "STORE_TARGET_LIST", 65: "ESCORT_RESUME",
    66: "SET_ORIENTATION", 67: "CREATE_TIMED_EVENT", 68: "PLAYMOVIE",
    69: "MOVE_TO_POS", 70: "RESPAWN_TARGET", 71: "EQUIP",
    72: "CLOSE_GOSSIP", 73: "TRIGGER_TIMED_EVENT", 74: "REMOVE_TIMED_EVENT",
    75: "ADD_AURA", 76: "OVERRIDE_SCRIPT_BASE_OBJECT",
    77: "RESET_SCRIPT_BASE_OBJECT", 78: "CALL_SCRIPT_RESET",
    79: "SET_RANGED_MOVEMENT", 80: "CALL_TIMED_ACTIONLIST",
    81: "SET_NPC_FLAG", 82: "ADD_NPC_FLAG", 83: "REMOVE_NPC_FLAG",
    84: "SIMPLE_TALK", 85: "SELF_CAST", 86: "CROSS_CAST",
    87: "CALL_RANDOM_TIMED_ACTIONLIST", 88: "CALL_RANDOM_RANGE_TIMED_ACTIONLIST",
    89: "RANDOM_MOVE", 90: "SET_UNIT_FIELD_BYTES_1", 91: "REMOVE_UNIT_FIELD_BYTES_1",
    92: "INTERRUPT_SPELL", 93: "SEND_GO_CUSTOM_ANIM", 94: "SET_DYNAMIC_FLAG",
    95: "ADD_DYNAMIC_FLAG", 96: "REMOVE_DYNAMIC_FLAG", 97: "JUMP_TO_POS",
    98: "SEND_GOSSIP_MENU", 99: "GO_SET_LOOT_STATE",
    100: "SEND_TARGET_TO_TARGET", 101: "SET_HOME_POS", 102: "SET_HEALTH_REGEN",
    103: "SET_ROOT", 104: "SET_GO_FLAG", 105: "ADD_GO_FLAG",
    106: "REMOVE_GO_FLAG", 107: "SUMMON_CREATURE_GROUP",
    108: "SET_POWER", 109: "ADD_POWER", 110: "REMOVE_POWER",
    111: "GAME_EVENT_STOP", 112: "GAME_EVENT_START",
    113: "START_CLOSEST_WAYPOINT", 114: "RISE_UP", 115: "RANDOM_SOUND",
    116: "SET_CORPSE_DELAY", 117: "DISABLE_EVADE", 118: "GO_SET_GO_STATE",
    121: "SET_SIGHT_DIST", 122: "FLEE", 123: "ADD_THREAT",
    124: "LOAD_EQUIPMENT", 125: "TRIGGER_RANDOM_TIMED_EVENT",
    126: "REMOVE_ALL_GAMEOBJECTS", 131: "SPAWN_SPAWNGROUP",
    132: "DESPAWN_SPAWNGROUP", 134: "INVOKER_CAST",
    135: "PLAY_CINEMATIC", 136: "SET_MOVEMENT_SPEED", 142: "SET_HEALTH_PCT",
    201: "MOVE_TO_POS_TARGET", 203: "EXIT_VEHICLE",
    204: "SET_UNIT_MOVEMENT_FLAGS", 205: "SET_COMBAT_DISTANCE",
    206: "DISMOUNT", 207: "SET_HOVER", 208: "ADD_IMMUNITY",
    209: "REMOVE_IMMUNITY", 210: "FALL", 211: "SET_EVENT_FLAG_RESET",
    212: "STOP_MOTION", 213: "NO_ENVIRONMENT_UPDATE",
    214: "ZONE_UNDER_ATTACK", 215: "LOAD_GRID", 216: "MUSIC",
    217: "RANDOM_MUSIC", 218: "CUSTOM_CAST", 219: "CONE_SUMMON",
    220: "PLAYER_TALK", 221: "VORTEX_SUMMON", 222: "CU_ENCOUNTER_START",
    223: "DO_ACTION", 224: "ATTACK_STOP", 225: "SET_GUID",
    226: "SCRIPTED_SPAWN", 227: "SET_SCALE", 228: "SUMMON_RADIAL",
    229: "PLAY_SPELL_VISUAL", 230: "FOLLOW_GROUP",
    231: "ORIENTATION_TARGET", 232: "WAYPOINT_START",
    233: "WAYPOINT_DATA_RANDOM", 234: "MOVEMENT_STOP",
    235: "MOVEMENT_PAUSE", 236: "MOVEMENT_RESUME",
    237: "WORLD_SCRIPT", 238: "DISABLE_REWARD", 239: "SET_ANIM_TIER",
    240: "SET_GOSSIP_MENU", 241: "SUMMON_GAMEOBJECT_GROUP",
}

_SAI_TARGET_NAMES = {
    0: "NONE", 1: "SELF", 2: "VICTIM",
    3: "HOSTILE_SECOND_AGGRO", 4: "HOSTILE_LAST_AGGRO",
    5: "HOSTILE_RANDOM", 6: "HOSTILE_RANDOM_NOT_TOP",
    7: "ACTION_INVOKER", 8: "POSITION",
    9: "CREATURE_RANGE", 10: "CREATURE_GUID", 11: "CREATURE_DISTANCE",
    12: "STORED", 13: "GAMEOBJECT_RANGE", 14: "GAMEOBJECT_GUID",
    15: "GAMEOBJECT_DISTANCE", 16: "INVOKER_PARTY",
    17: "PLAYER_RANGE", 18: "PLAYER_DISTANCE",
    19: "CLOSEST_CREATURE", 20: "CLOSEST_GAMEOBJECT",
    21: "CLOSEST_PLAYER", 22: "ACTION_INVOKER_VEHICLE",
    23: "OWNER_OR_SUMMONER", 24: "THREAT_LIST",
    25: "CLOSEST_ENEMY", 26: "CLOSEST_FRIENDLY",
    27: "LOOT_RECIPIENTS", 28: "FARTHEST",
    29: "VEHICLE_PASSENGER",
    201: "PLAYER_WITH_AURA", 202: "RANDOM_POINT",
    203: "ROLE_SELECTION", 204: "SUMMONED_CREATURES",
    205: "INSTANCE_STORAGE", 206: "FORMATION",
}

_SAI_SOURCE_TYPE_NAMES = {
    0: "CREATURE", 1: "GAMEOBJECT", 2: "AREATRIGGER", 9: "TIMED_ACTIONLIST",
}


# ============================================================================
# Emote enum mappings (SharedDefines.h)
# ============================================================================
_TEXT_EMOTE_NAMES = {
    1: "AGREE", 2: "AMAZE", 3: "ANGRY", 4: "APOLOGIZE", 5: "APPLAUD",
    6: "BASHFUL", 7: "BECKON", 8: "BEG", 9: "BITE", 10: "BLEED",
    11: "BLINK", 12: "BLUSH", 13: "BONK", 14: "BORED", 15: "BOUNCE",
    16: "BRB", 17: "BOW", 18: "BURP", 19: "BYE", 20: "CACKLE",
    21: "CHEER", 22: "CHICKEN", 23: "CHUCKLE", 24: "CLAP", 25: "CONFUSED",
    26: "CONGRATULATE", 27: "COUGH", 28: "COWER", 29: "CRACK", 30: "CRINGE",
    31: "CRY", 32: "CURIOUS", 33: "CURTSEY", 34: "DANCE", 35: "DRINK",
    36: "DROOL", 37: "EAT", 38: "EYE", 39: "FART", 40: "FIDGET",
    41: "FLEX", 42: "FROWN", 43: "GASP", 44: "GAZE", 45: "GIGGLE",
    46: "GLARE", 47: "GLOAT", 48: "GREET", 49: "GRIN", 50: "GROAN",
    51: "GROVEL", 52: "GUFFAW", 53: "HAIL", 54: "HAPPY", 55: "HELLO",
    56: "HUG", 57: "HUNGRY", 58: "KISS", 59: "KNEEL", 60: "LAUGH",
    61: "LAYDOWN", 62: "MESSAGE", 63: "MOAN", 64: "MOON", 65: "MOURN",
    66: "NO", 67: "NOD", 68: "NOSEPICK", 69: "PANIC", 70: "PEER",
    71: "PLEAD", 72: "POINT", 73: "POKE", 74: "PRAY", 75: "ROAR",
    76: "ROFL", 77: "RUDE", 78: "SALUTE", 79: "SCRATCH", 80: "SEXY",
    81: "SHAKE", 82: "SHOUT", 83: "SHRUG", 84: "SHY", 85: "SIGH",
    86: "SIT", 87: "SLEEP", 88: "SNARL", 89: "SPIT", 90: "STARE",
    91: "SURPRISED", 92: "SURRENDER", 93: "TALK", 94: "TALKEX", 95: "TALKQ",
    96: "TAP", 97: "THANK", 98: "THREATEN", 99: "TIRED", 100: "VICTORY",
    101: "WAVE", 102: "WELCOME", 103: "WHINE", 104: "WHISTLE", 105: "WORK",
    106: "YAWN", 107: "BOGGLE", 108: "CALM", 109: "COLD", 110: "COMFORT",
    111: "CUDDLE", 112: "DUCK", 113: "INSULT", 114: "INTRODUCE", 115: "JK",
    116: "LICK", 117: "LISTEN", 118: "LOST", 119: "MOCK", 120: "PONDER",
    121: "POUNCE", 122: "PRAISE", 123: "PURR", 124: "PUZZLE", 125: "RAISE",
    126: "READY", 127: "SHIMMY", 128: "SHIVER", 129: "SHOO", 130: "SLAP",
    131: "SMIRK", 132: "SNIFF", 133: "SNUB", 134: "SOOTHE", 135: "STINK",
    136: "TAUNT", 137: "TEASE", 138: "THIRSTY", 139: "VETO", 140: "SNICKER",
    141: "STAND", 142: "TICKLE", 143: "VIOLIN", 163: "SMILE", 183: "RASP",
    203: "PITY", 204: "GROWL",
}

_ANIM_EMOTE_NAMES = {
    0: "NONE", 1: "TALK", 2: "BOW", 3: "WAVE", 4: "CHEER",
    5: "EXCLAMATION", 6: "QUESTION", 7: "EAT", 10: "DANCE_STATE",
    11: "LAUGH", 12: "SLEEP_STATE", 13: "SIT_STATE", 14: "RUDE",
    15: "ROAR", 16: "KNEEL", 17: "KISS", 18: "CRY", 19: "CHICKEN",
    20: "BEG", 21: "APPLAUD", 22: "SHOUT", 23: "FLEX", 24: "SHY",
    25: "POINT", 26: "STAND_STATE", 27: "READY_UNARMED_STATE", 28: "WORK_SHEATHED_STATE",
    29: "POINT_STATE", 30: "NONE_STATE", 33: "WOUND", 34: "WOUND_CRITICAL",
    35: "ATTACK_UNARMED", 36: "ATTACK1H", 37: "ATTACK2HTIGHT", 38: "ATTACK2H_LOOSE",
    39: "PARRY_UNARMED", 43: "PARRY_SHIELD", 44: "READY_UNARMED_ONESHOT", 45: "READY1H",
    48: "READY_BOW", 50: "SPELL_PRECAST", 51: "SPELL_CAST", 53: "BATTLE_ROAR",
    54: "SPECIALATTACK1H", 60: "KICK", 61: "ATTACK_THROWN", 64: "STUN_STATE",
    65: "DEAD_STATE", 66: "SALUTE", 68: "KNEEL_STATE", 69: "USE_STANDING_STATE",
    70: "WAVE_NO_SHEATHE", 71: "CHEER_NO_SHEATHE", 92: "EAT_NO_SHEATHE",
    93: "STUN_NO_SHEATHE_STATE", 94: "DANCE", 113: "SALUTE_NO_SHEATH",
    133: "USE_STANDING_NO_SHEATHE_STATE", 153: "LAUGH_NO_SHEATHE",
    173: "WORK_STATE", 193: "SPELL_PRECAST_STATE", 213: "READY_RIFLE",
    214: "READY_RIFLE_STATE", 233: "WORK_MINING_STATE", 234: "WORK_CHOPWOOD_STATE",
    253: "APPLAUD_STATE", 254: "LIFTOFF", 273: "YES", 274: "NO",
    275: "TRAIN", 293: "LAND", 313: "AT_EASE_STATE", 333: "READY1H_STATE",
    353: "SPELL_KNEEL_START_STATE", 373: "SUBMERGED_STATE", 374: "SUBMERGE",
    375: "READY2H_STATE", 376: "READY_BOW_STATE", 377: "MOUNT_SPECIAL",
    378: "TALK_STATE", 379: "FISHING_STATE", 380: "FISHING", 381: "LOOT",
    382: "WHIRLWIND_STATE", 383: "DROWNED_STATE", 384: "HOLD_BOW_STATE",
    385: "HOLD_RIFLE_STATE", 386: "HOLD_THROWN_STATE", 387: "DROWN",
    388: "STOMP", 389: "ATTACK_OFF", 390: "ATTACK_OFF_PIERCE",
    391: "ROAR_STATE", 392: "LAUGH_STATE", 393: "CREATURE_SPECIAL",
    394: "JUMPLANDRUN", 395: "JUMPEND", 396: "TALK_NO_SHEATHE",
    397: "POINT_NO_SHEATHE", 398: "CANNIBALIZE_STATE", 399: "JUMPSTART",
    400: "DANCESPECIAL_STATE", 401: "DANCESPECIAL", 402: "CUSTOM_SPELL_01",
    403: "CUSTOM_SPELL_02", 404: "CUSTOM_SPELL_03", 405: "CUSTOM_SPELL_04",
}


# ============================================================================
# Achievement criteria enum mappings
# ============================================================================
_AC_TYPE_NAMES = {
    0: "TYPE_NONE",
    1: "TYPE_T_CREATURE",
    2: "TYPE_T_PLAYER_CLASS_RACE",
    3: "TYPE_T_PLAYER_LESS_HEALTH",
    4: "TYPE_T_PLAYER_DEAD",
    5: "TYPE_S_AURA",
    6: "TYPE_S_AREA",
    7: "TYPE_T_AURA",
    8: "TYPE_VALUE",
    9: "TYPE_T_LEVEL",
    10: "TYPE_T_GENDER",
    11: "TYPE_SCRIPT",
    12: "TYPE_MAP_DIFFICULTY",
    13: "TYPE_MAP_PLAYER_COUNT",
    14: "TYPE_T_TEAM",
    15: "TYPE_S_DRUNK",
    16: "TYPE_HOLIDAY",
    17: "TYPE_BG_LOSS_TEAM_SCORE",
    18: "TYPE_INSTANCE_SCRIPT",
    19: "TYPE_S_EQUIPED_ITEM",
    20: "TYPE_MAP_ID",
    21: "TYPE_S_PLAYER_CLASS_RACE",
    22: "TYPE_NTH_BIRTHDAY",
    23: "TYPE_S_KNOWN_TITLE",
    24: "TYPE_BG_WIN_TEAM_SCORE",
    25: "TYPE_S_ITEM_QUALITY",
}

_AC_RACE_NAMES = {
    1: "Human", 2: "Orc", 3: "Dwarf", 4: "NightElf", 5: "Undead", 6: "Tauren",
    7: "Gnome", 8: "Troll", 10: "BloodElf", 11: "Draenei",
}

_AC_COMP_TYPES = {0: ">=", 1: "<=", 2: "==", 3: "!=", 4: "bitand"}
_AC_DRUNK_STATES = {0: "normal", 1: "slightly_tipsy", 2: "very_drunk", 3: "drunk"}
